config/routes.rb
CooltoolSales::Application.routes.draw do
  get "accounts/index"
  resources :upload_files

  get "welcome/index"
  resources :sales

  resources :countries

  resources :app_versions

  resources :apps

  post "upload/upload"
  get "upload/index"

  root 'welcome#index'

end

app/models/upload_file.rb
class UploadFile < ActiveRecord::Base
  has_many :sales, dependent: :destroy
  scope :recently_uploaded, lambda { where("created_at >= ?", Date.today().days_ago(5)) }
  
  
  def self.sales_in_date_range(from, to)
    where("sales_date >= ? and sales_date <= ?", from, to)
  end
  
  def to_sales_grid_row
    apps = App.all.order("short_app_name")
    row = Array.new(apps.count)
    
    app_counter = 0
    apps.each do |app|
      row[app_counter] = 0
      sales.each do |sale|
        if sale.app_version.app == app
          unless sale.proceeds_in_dollars.nil? or sale.units.nil?
            row[app_counter] += sale.proceeds_in_dollars * sale.units
          end
        end
      end
      app_counter += 1
    end
    row
  end
  
  def total_sales
    total = 0
    sales.each do |sale|
      unless sale.proceeds_in_dollars.nil? or sale.units.nil?
        total += sale.proceeds_in_dollars * sale.units
      end
    end
    total
  end
end

app/controllers/upload_files_controller.rb
class UploadFilesController < ApplicationController
  before_action :set_upload_file, only: [:show, :edit, :update, :destroy]

  # GET /upload_files
  # GET /upload_files.json
  def index
    @upload_files = UploadFile.all
  end

  # GET /upload_files/1
  # GET /upload_files/1.json
  def show
  end

  # GET /upload_files/new
  def new
    @upload_file = UploadFile.new
  end

  # GET /upload_files/1/edit
  def edit
  end

  # POST /upload_files
  # POST /upload_files.json
  def create
    @upload_file = UploadFile.new(upload_file_params)

    respond_to do |format|
      if @upload_file.save
        format.html { redirect_to @upload_file, notice: 'Upload file was successfully created.' }
        format.json { render action: 'show', status: :created, location: @upload_file }
      else
        format.html { render action: 'new' }
        format.json { render json: @upload_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upload_files/1
  # PATCH/PUT /upload_files/1.json
  def update
    respond_to do |format|
      if @upload_file.update(upload_file_params)
        format.html { redirect_to @upload_file, notice: 'Upload file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upload_files/1
  # DELETE /upload_files/1.json
  def destroy
    @upload_file.destroy
    respond_to do |format|
      format.html { redirect_to upload_files_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload_file
      @upload_file = UploadFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_file_params
      params.require(:upload_file).permit(:filename)
    end
end

app/helpers/upload_files_helper.rb
module UploadFilesHelper
end

app/views/upload_files/_form.html.erb
<%= form_for @upload_file, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :filename, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :filename, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sales_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sales_date, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                upload_files_path, :class => 'btn' %>
  </div>
<% end %>

app/views/upload_files/_upload_file.html.erb
<%= content_tag :tr do -%>
	<td nowrap>
		<%= upload_file.sales_date %>
	</td>

	<% upload_file.to_sales_grid_row.each do |sale| %>
		<%= content_tag :td do %>
			<% unless sale.nil? or sale == 0 %>
				<%= content_tag :div, :class => "text-right" do %>
					<%= number_to_currency(sale) %>
				<% end %>
			<% end %>
		<% end %>
	<% end %>

	<td align="right">
		<%= content_tag :div, :class => "text-right" do %>
			<%= number_to_currency(upload_file.total_sales) %>
		<% end %>
	</td>
<% end -%>

app/views/upload_files/_upload_files_collection.html.erb
<style type="text/css">
.even {
  background-color: #f0f0f0;
}
</style>

<table border="1" cellspacing="0" class="table table-striped table-condensed">
	<%= content_tag :tr do -%>
		<th>Date</th>
		<% apps.each do |app| %>
			<th><%= link_to app.short_app_name, edit_app_path(app) %> </th>
		<% end %>
		<th>Daily Total</th>
	<% end -%>
	<%= render upload_files %>
</table>

app/views/upload_files/edit.html.erb
<%- model_class = UploadFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/upload_files/index.html.erb
<%- model_class = UploadFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:filename) %></th>
      <th><%= model_class.human_attribute_name(:sales_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @upload_files.each do |upload_file| %>
      <tr>
        <td><%= link_to upload_file.id, upload_file_path(upload_file) %></td>
        <td><%= upload_file.filename %></td>
        <td><%= upload_file.sales_date %></td>
        <td><%=l upload_file.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_upload_file_path(upload_file), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      upload_file_path(upload_file),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_upload_file_path,
            :class => 'btn btn-primary' %>

app/views/upload_files/new.html.erb
<%- model_class = UploadFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/upload_files/show.html.erb
<%- model_class = UploadFile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:filename) %>:</strong></dt>
  <dd><%= @upload_file.filename %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sales_date) %>:</strong></dt>
  <dd><%= @upload_file.sales_date %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              upload_files_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_upload_file_path(@upload_file), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              upload_file_path(@upload_file),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>