config/routes.rb
CooltoolSales::Application.routes.draw do
  get "accounts/index"
  resources :upload_files

  get "welcome/index"
  resources :sales

  resources :countries

  resources :app_versions

  resources :apps

  post "upload/upload"
  get "upload/index"

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
include ActionView::Helpers::NumberHelper

class WelcomeController < ApplicationController
  def index
    
    ActiveRecord::Base.logger.level = 1
    
    event = params[:the_from_date]    
    if event.nil?
      @filter_from = Date.today.months_ago(1)
    else
      @filter_from = Date.new event["(1i)"].to_i, event["(2i)"].to_i, event["(3i)"].to_i
    end

    event = params[:the_to_date]    
    if event.nil?
      @filter_to = Date.today 
    else      
      @filter_to = Date.new event["(1i)"].to_i, event["(2i)"].to_i, event["(3i)"].to_i
    end

    
    @apps = App.all.order("short_app_name")
    @upload_files = UploadFile.sales_in_date_range(@filter_from, @filter_to).order("sales_date desc")
    @filecount = UploadFile.all.count
    @foreign_currency_sales = Sale.unconverted_foreign_currency
    @total_sales = 0

    legend = [ ]
    @data = [ ]
    @title = "App Sales from #{@filter_from} through #{@filter_to}"

    @units_legend = [ ]
    @units_data = [ ]
    @units_title = "Unit Sales from #{@filter_from} through #{@filter_to}"

    app_sales_total = [ ]
    @apps.each do |app|
      sales_total = app.sales_total_within_date_range(@filter_from, @filter_to)
      if sales_total > 0
        @total_sales += sales_total
        label = "#{app.short_app_name} "
        
        app_sales_total << sales_total
        legend << label
        @data << sales_total
      end

      units_total = app.units_total_within_date_range(@filter_from, @filter_to)
      if units_total > 0
        label = "#{app.short_app_name} (#{units_total})"
        @units_legend << label
        @units_data << units_total
      end

      unless @total_sales == 0 
        @legend = legend.zip(app_sales_total).map do |legend, sales| 
          legend = "#{legend} (#{number_to_currency(sales)}, #{number_to_percentage(sales/@total_sales*100, precision: 1)})" 
        end
      end
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<style type="text/css">
.datetime select:nth-child(1){
  width: 130px;
  text-indent: 15px; 
}

.datetime select:nth-child(2) {
  width: 60px;
  text-indent: 5px;
}

.datetime select:nth-child(3) {
  width: 100px;
  text-indent: 15px;
}
</style>


<div class="page-header">
  <h1>Sales Summary</h1>
</div>
<% unless flash[:error].nil? %>
	<div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<%= form_tag(root_path, :method => :get, :class => "form-inline") do %>
<%= label_tag("Filter all data on page to") %><br/>
	<%= label_tag(:the_from_date, "From:") %>
	<%= content_tag :span, :class => "datetime" do %>
		<%= date_select(:the_from_date, "", 
			:default => @filter_from, 
			:order => [:month, :day, :year],
			:size => 5, 
			:html=>{:class => "input-mini"}) %>
	<% end %>
	
	<%= label_tag(:the_to_date, "To:") %>
	<%= content_tag :span, :class => "datetime" do %>
		<%= date_select(:the_to_date, "", 
			:default => @filter_to, 
			:order => [:month, :day, :year],
			:html=>{:class => "input-mini"}) %>
	<% end %>
	
	<%= submit_tag("Filter") %>
<% end %>

<% unless @foreign_currency_sales.count == 0 %>
	<%= content_tag :table, { :border => 1, :cellspacing => 0, :style => "border-color:#f0f0f0;"} do %>
		<tr><th colspan="3">Foreign Currencies Needing Exchange</th></tr>
		<tr><th>App</th><th>Proceeds</th></tr>
		<% @foreign_currency_sales.each do |sale| %>
			<%= content_tag :tr do %>
				<%= content_tag( :td, sale.app_version.app.title ) %>
				<%= content_tag( :td, link_to("#{sale.developer_proceeds} (#{sale.currency_of_proceeds})", edit_sale_path(sale)), { :align => "right" } ) %>
			<% end %>
		<% end %>
	<% end %>
<% end %>


<%= content_tag :table, { :border => 0, :cellspacing => 0, :class => "table table-condensed" } do %>
	<%= content_tag :tr do %>
		<%= content_tag :td do %>
			<%= content_tag :table, { :border => 1, :cellspacing => 0, :style => "border-color:#f0f0f0;"} do %>
				<tr><th colspan="3">Sales from <%= @filter_from %> through <%= @filter_to %> </th></tr>
				<tr><th>App</th><th>Units</th><th>Sales</th></tr>
				<% @apps.each do |app| %>
					<tr>
						<td nowrap>
								<%= link_to app.title, edit_app_path(app) %> 
								(<%= app.short_app_name %>)
						</td>
						<td>
							<%= content_tag :div, :class => "text-right" do %>
								<%= number_with_delimiter(app.units_total_within_date_range(@filter_from, @filter_to), :delimiter => ',') %>
							<% end %>
						</td>
						<td>
							<%= content_tag :div, :class => "text-right" do %>
								<%= number_to_currency(app.sales_total_within_date_range(@filter_from, @filter_to)) %>
							<% end %>
						</td>
					</tr>
				<% end %>
				<tr><td colspan="2" align="right">Total</td><td><%= number_to_currency(@total_sales) %></td></tr>
			<% end %>
		<% end %>
		<%= content_tag :td, :nowrap => true do %>
			<img src="<%= Gchart.pie(:title => @title, 
										:labels => @legend, 
										:data => @data, 
										:bg => 'efefef',
										:size => '700x370',
										:background => 'E0E0E0', 
										:chart_background => 'F0F0F0') %>">
			<img src="<%= Gchart.pie(:title => @units_title, 
										:labels => @units_legend, 
										:data => @units_data, 
										:bg => 'efefef',
										:size => '700x370',
										:background => 'E0E0E0', 
										:chart_background => 'F0F0F0') %>">
		<% end %>
	<% end %>
<% end %>




<%= render partial: "upload_files/upload_files_collection", locals: {apps: @apps, upload_files: @upload_files} %>