config/routes.rb
CooltoolSales::Application.routes.draw do
  get "accounts/index"
  resources :upload_files

  get "welcome/index"
  resources :sales

  resources :countries

  resources :app_versions

  resources :apps

  post "upload/upload"
  get "upload/index"

  root 'welcome#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :country
  belongs_to :app_version
  belongs_to :upload_file
  before_save :before_validation_set_defaults#, :only => [ :create, :update ]
  
  scope :unconverted_foreign_currency, lambda { where(:proceeds_in_dollars => nil).where("proceeds <> 0") }
  
  def developer_proceeds
    if is_paid_transaction
      if proceeds_in_dollars.nil? 
        proceeds.to_f
      else
        proceeds_in_dollars
      end
    else
      0
    end
  end
  
  def is_paid_transaction
    if product_type_identifier[0, 1] == "1" 
      return true 
    else 
      return false
    end
  end
  
  def developer_proceeds_is_usd
    not proceeds_in_dollars.nil? or proceeds == 0
  end
  
  def before_validation_set_defaults
    if is_paid_transaction
      if self.currency_of_proceeds == "USD"
        self.proceeds_in_dollars = proceeds
      else
        self.proceeds_in_dollars = app_version.app.default_proceeds_in_dollars
      end
    end
  end  
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all.order("sales_date desc").paginate(:page => params[:page])
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  # def create
  #   @sale = Sale.new(sale_params)
  # 
  #   respond_to do |format|
  #     if @sale.save
  #       format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @sale }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @sale.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:units, :proceeds, :customer_currency, :country_id, :currency_of_proceeds, :customer_price, :proceeds_in_dollars)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for @sale, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :units, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :units, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :proceeds, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :proceeds, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :customer_currency, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_currency, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :currency_of_proceeds, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :currency_of_proceeds, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :customer_price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :customer_price, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :app_version_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :app_version_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sales_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sales_date, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :upload_file_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :upload_file_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :proceeds_in_dollars, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :proceeds_in_dollars, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :product_type_identifier, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :product_type_identifier, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sales_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %> <small>Newest first</small></h1>
</div>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:units) %></th>
      <th><%= model_class.human_attribute_name(:proceeds) %></th>
      <th><%= model_class.human_attribute_name(:customer_currency) %></th>
      <th><%= model_class.human_attribute_name(:country_id) %></th>
      <th><%= model_class.human_attribute_name(:currency_of_proceeds) %></th>
      <th><%= model_class.human_attribute_name(:customer_price) %></th>
      <th><%= model_class.human_attribute_name(:app_version_id) %></th>
      <th><%= model_class.human_attribute_name(:sales_date) %></th>
      <th><%= model_class.human_attribute_name(:upload_file_id) %></th>
      <th><%= model_class.human_attribute_name(:proceeds_in_dollars) %></th>
      <th><%= model_class.human_attribute_name(:product_type_identifier) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= sale.units %></td>
        <td><%= sale.proceeds %></td>
        <td><%= sale.customer_currency %></td>
        <td><%= sale.country_id %></td>
        <td><%= sale.currency_of_proceeds %></td>
        <td><%= sale.customer_price %></td>
        <td><%= sale.app_version_id %></td>
        <td><%= sale.sales_date %></td>
        <td><%= sale.upload_file_id %></td>
        <td><%= sale.proceeds_in_dollars %></td>
        <td><%= sale.product_type_identifier %></td>
        <td><%=l sale.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sale_path(sale), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
	<tr>
		<td colspan="10">
			<%= will_paginate @sales %>
		</td>
	</tr>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<%- model_class = Sale -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:units) %>:</strong></dt>
  <dd><%= @sale.units %></dd>
  <dt><strong><%= model_class.human_attribute_name(:proceeds) %>:</strong></dt>
  <dd><%= @sale.proceeds %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_currency) %>:</strong></dt>
  <dd><%= @sale.customer_currency %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country_id) %>:</strong></dt>
  <dd><%= @sale.country_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:currency_of_proceeds) %>:</strong></dt>
  <dd><%= @sale.currency_of_proceeds %></dd>
  <dt><strong><%= model_class.human_attribute_name(:customer_price) %>:</strong></dt>
  <dd><%= @sale.customer_price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:app_version_id) %>:</strong></dt>
  <dd><%= @sale.app_version_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sales_date) %>:</strong></dt>
  <dd><%= @sale.sales_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:upload_file_id) %>:</strong></dt>
  <dd><%= @sale.upload_file_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:proceeds_in_dollars) %>:</strong></dt>
  <dd><%= @sale.proceeds_in_dollars %></dd>
  <dt><strong><%= model_class.human_attribute_name(:product_type_identifier) %>:</strong></dt>
  <dd><%= @sale.product_type_identifier %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>